run_name: OLMo-1B-qp
seed: 6199
dry_run: false
time_limit: 604800.0 # 7 day

wandb:
 name: ${run_name}
 project: olmo_001
 entity: qiupeng
 log_interval: 1

model:
  d_model: 2048
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: true  # not available on AMD
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: false
  include_bias: false
  block_type: sequential
  layer_norm_type: default
  layer_norm_with_affine: false
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: false
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 2048 #2048
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 50279
  pad_token_id: 1
  init_device: meta
  init_fn: mitchell

compile: true  # causes instability on AMD GPUs

optimizer:
  name: adamw
  learning_rate: 1.0e-4
  weight_decay: 0.1
  betas:
  - 0.9
  - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_eleuther-ai-gpt-neox-20b-pii-special.json
  truncate_direction: right

save_folder: save
save_overwrite: true
# Sharded checkpoints (best for restarts)
save_interval: 1000
save_num_checkpoints_to_keep: 9
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 10000
save_num_unsharded_checkpoints_to_keep: -1

#load_path: save_folder2/latest

max_duration: 739_328  # 3.1T tokens
global_train_batch_size: 2048 #2048
device_train_microbatch_size: 8 #8

precision: amp_bf16

fsdp:
  wrapping_strategy: null
  precision: mixed

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 20

data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: 16
  persistent_workers: true
  timeout: 0
  datasets:
    starcode:
      mix_rate: 0.5
      path: /root/olmo_datasets_tool/olmo_npy/starcode
    Wikipedia:
      mix_rate: 0.5
      path: /root/olmo_datasets_tool/olmo_npy/Wikipedia
    ArXiv:
      mix_rate: 0.5
      path: /root/olmo_datasets_tool/olmo_npy/ArXiv
